before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  binary: viddy
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  ldflags:
  - -s -w -X main.version={{.Version}}
archives:
  - id: replace
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
- tap:
    owner: sachaos
    name: homebrew-tap
  folder: Formula
  homepage: https://github.com/sachaos/viddy
  description: Modern waach command. Viddy well, gopher. Viddy well.
  skip_upload: auto
  test: |
    system "#{bin}/viddy", "--version"
